---
title: "Resume"
output: html_document
hidedate: true
hiderelated: true
hidediscus: true
---

My name is Jacky Xia. Few years after being born in New York City, I moved to a small town in west Texas called San Angelo where I would spend most of my adolescence. Shortly after I graduated high school, I moved to McKinney, Texas (a suburb north of Dallas), but I didn't spend long there since I soon went to attend the University of Texas at Austin. 

At UT, I would go on to get a BS in biochemistry with a professional health certificate for science majors. After realizing that I would be on track to graduate early and also realizing that I was not quite ready to move past college, I decided to also get a BS in human biology with a minor in business. If everything goes well, I will be graduating in the Spring 2021 semester (this one!) 

As you can see from my choice of majors, I have a keen interest in the chemistry of biology. These interests have taken a part of my life through my involvement with the FRI program (Freshman Research Initiative) and my aspirations to be involved in a field related to biochemistry (ideally health pharmacy but I am open to other options). I don't have much work experience with the only job I had being a TA for the FRI program I once took apart in. All of these combined gives me the analytical skills to understand processes thoroughly, conduct them efficiently, and apply the results meaningfully. These skills have been recognized by my FRI professor as a Graduate of Distinction. 

Want to know more or get into contact? Please send me an email at jackyxia@utexas.edu